language: generic

# super user permision
sudo: required

services:
  - docker
#need to occure before deploy or un our test
# tag to avoid manual copy id github username/name can use any name for tagging.

before_install:
  - docker build -t rajeka/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rajeka/docker-react npm run test
